"""initial migration

Revision ID: 001
Revises: 
Create Date: 2024-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('telegram_id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(), nullable=True),
        sa.Column('first_name', sa.String(), nullable=True),
        sa.Column('last_name', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('telegram_id')
    )
    op.create_table('conversion_jobs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('input_filename', sa.String(), nullable=False),
        sa.Column('output_filename', sa.String(), nullable=True),
        sa.Column('input_format', sa.String(), nullable=False),
        sa.Column('output_format', sa.String(), nullable=False),
        sa.Column('status', postgresql.ENUM('pending', 'processing', 'completed', 'failed', name='jobstatus'), nullable=False),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversion_jobs_id', 'conversion_jobs', ['id'], unique=False)
    op.create_table('file_formats',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('extension', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('category', sa.String(), nullable=False),
        sa.Column('is_input', sa.Boolean(), nullable=True),
        sa.Column('is_output', sa.Boolean(), nullable=True),
        sa.Column('priority', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('extension')
    )
    # ### end Alembic commands ###

    # Insert initial data for supported formats
    formats = [
        # Input formats
        {'extension': 'pdf', 'name': 'PDF Document', 'category': 'document', 'is_input': True, 'is_output': False, 'priority': 1},
        # Output formats
        {'extension': 'docx', 'name': 'Word Document', 'category': 'document', 'is_input': False, 'is_output': True, 'priority': 2},
        {'extension': 'xlsx', 'name': 'Excel Spreadsheet', 'category': 'spreadsheet', 'is_input': False, 'is_output': True, 'priority': 3},
        {'extension': 'pptx', 'name': 'PowerPoint Presentation', 'category': 'presentation', 'is_input': False, 'is_output': True, 'priority': 4},
        {'extension': 'txt', 'name': 'Plain Text', 'category': 'document', 'is_input': False, 'is_output': True, 'priority': 5},
        {'extension': 'rtf', 'name': 'Rich Text Format', 'category': 'document', 'is_input': False, 'is_output': True, 'priority': 6},
        {'extension': 'jpeg', 'name': 'JPEG Image', 'category': 'image', 'is_input': False, 'is_output': True, 'priority': 7},
        {'extension': 'png', 'name': 'PNG Image', 'category': 'image', 'is_input': False, 'is_output': True, 'priority': 8},
        {'extension': 'html', 'name': 'HTML Document', 'category': 'web', 'is_input': False, 'is_output': True, 'priority': 9},
    ]
    
    op.bulk_insert(
        sa.table('file_formats',
            sa.column('extension', sa.String),
            sa.column('name', sa.String),
            sa.column('category', sa.String),
            sa.column('is_input', sa.Boolean),
            sa.column('is_output', sa.Boolean),
            sa.column('priority', sa.Integer)
        ),
        formats
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_formats')
    op.drop_index('ix_conversion_jobs_id', table_name='conversion_jobs')
    op.drop_table('conversion_jobs')
    op.drop_table('users')
    # ### end Alembic commands ###
    
    # Drop enum type
    op.execute('DROP TYPE jobstatus')